# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xHqnHEDZi9nbW-Mx3Gox_ysN3Y3yRog
"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    silhouette_score
)

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.cluster import KMeans
import joblib

sns.set(style="whitegrid")

# 0. Paths and folders
BASE_DIR = os.getcwd()
DATA_DIR = BASE_DIR
RESULTS_DIR = os.path.join(BASE_DIR, "results")
MODELS_DIR = os.path.join(BASE_DIR, "models")

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

DATA_PATH = os.path.join(DATA_DIR, "netflix_titles.csv")

# 1. Load dataset
print("Loading dataset from:", DATA_PATH)
df = pd.read_csv(DATA_PATH)
print("Shape:", df.shape)
print(df.head())

# 2. Basic EDA
print("\n=== INFO ===")
print(df.info())

print("\n=== Missing values per column ===")
print(df.isnull().sum().sort_values(ascending=False))

print("\n=== Type distribution ===")
print(df["type"].value_counts())

plt.figure(figsize=(4, 4))
ax = df["type"].value_counts().plot(kind="bar", title="Movie vs TV Show", rot=0)
ax.bar_label(ax.containers[0])
plt.tight_layout()
plt.savefig(os.path.join(RESULTS_DIR, "type_distribution.png"))
plt.close()

plt.figure(figsize=(8, 4))
df["release_year"].plot(kind="hist", bins=30, title="Release Year Distribution")
plt.xlabel("Release year")
plt.tight_layout()
plt.savefig(os.path.join(RESULTS_DIR, "release_year_hist.png"))
plt.close()

# 3. Feature Engineering
df = df.copy()

def parse_duration_minutes(x):
    if pd.isna(x): return np.nan
    m = re.search(r"(\d+)\s*min", str(x))
    return int(m.group(1)) if m else np.nan

def parse_seasons(x):
    if pd.isna(x): return np.nan
    m = re.search(r"(\d+)\s*Season", str(x))
    return int(m.group(1)) if m else 0

df["duration_minutes"] = df["duration"].apply(parse_duration_minutes)
df["seasons"] = df["duration"].apply(parse_seasons)

for col in ["listed_in", "description"]:
    df[col] = df[col].fillna("")

df["text_all"] = (
    df["listed_in"].str.lower().str.replace("[^a-z ]", " ", regex=True)
    + " "
    + df["description"].str.lower().str.replace("[^a-z ]", " ", regex=True)
)

y = df["type"].map({"Movie": 1, "TV Show": 0})
features_num = ["release_year", "duration_minutes", "seasons"]
features_cat = ["rating"]
feature_text = "text_all"

X = df[features_num + features_cat + [feature_text]]

# 4. Preprocessing pipeline & train/test split
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ohe", OneHotEncoder(handle_unknown="ignore")),
])

text_transformer = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=10000, ngram_range=(1,2), min_df=2)),
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, features_num),
        ("cat", categorical_transformer, features_cat),
        ("txt", text_transformer, feature_text),
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 5. Train 3 models
models = {
    "LogisticRegression": LogisticRegression(max_iter=200),
    "KNN": KNeighborsClassifier(n_neighbors=7),
    "DecisionTree": DecisionTreeClassifier(max_depth=15),
}

results = []

for name, clf in models.items():
    pipe = Pipeline([("prep", preprocess), ("model", clf)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    results.append((name, acc, f1))

    print(f"\n=== {name} ===")
    print("Accuracy:", acc, "| F1:", f1)
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(cm)
    disp.plot()
    plt.title(f"Confusion Matrix - {name}")
    plt.savefig(os.path.join(RESULTS_DIR, f"confusion_{name}.png"))
    plt.close()

print("\n=== MODEL COMPARISON ===")
print(pd.DataFrame(results, columns=["Model", "Accuracy", "F1"]))

# 6. GridSearchCV Tuning
logit_grid = {
    "model__C": [0.2, 0.5, 1.0, 2.0],
    "model__solver": ["lbfgs"],
}
logit_pipe = Pipeline([("prep", preprocess), ("model", LogisticRegression(max_iter=200))])

gs_logit = GridSearchCV(logit_pipe, logit_grid, cv=3, scoring="f1", n_jobs=-1)
gs_logit.fit(X_train, y_train)
print("Best Logistic Regression:", gs_logit.best_params_)

knn_grid = {
    "model__n_neighbors": [3,5,7,11,15],
    "model__weights": ["uniform", "distance"],
    "model__p": [1,2],
}
knn_pipe = Pipeline([("prep", preprocess), ("model", KNeighborsClassifier())])

gs_knn = GridSearchCV(knn_pipe, knn_grid, cv=3, scoring="f1", n_jobs=-1)
gs_knn.fit(X_train, y_train)
print("Best KNN:", gs_knn.best_params_)

# 7. Best model evaluation
best_model = gs_logit if gs_logit.best_score_ >= gs_knn.best_score_ else gs_knn
best_name = "LogisticRegression" if best_model is gs_logit else "KNN"

y_pred_best = best_model.predict(X_test)
print(f"Best model: {best_name}")
print(classification_report(y_test, y_pred_best))

best_path = os.path.join(MODELS_DIR, f"best_{best_name}.pkl")
joblib.dump(best_model, best_path)
print("Saved best model to:", best_path)

# 8. Clustering (K-Means)
tfidf = TfidfVectorizer(max_features=5000, min_df=3, ngram_range=(1,2))
X_text = tfidf.fit_transform(df["text_all"])

sil = {}
for k in range(3, 9):
    km = KMeans(n_clusters=k, n_init=10)
    labels = km.fit_predict(X_text)
    score = silhouette_score(X_text, labels)
    sil[k] = score

best_k = max(sil, key=sil.get)
print("Best K:", best_k)

km = KMeans(n_clusters=best_k, n_init=10)
clusters = km.fit_predict(X_text)

df_clust = df[["title", "listed_in", "type", "release_year"]]
df_clust["cluster"] = clusters

for c in range(best_k):
    print(f"\n=== CLUSTER {c} ===")
    print(df_clust[df_clust["cluster"] == c].head(10))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(5,4))
ax = df['type'].value_counts().plot(kind='bar', rot=0)
ax.set_title("Distribution of content types")
ax.set_xlabel("Type")
ax.set_ylabel("Count")
ax.bar_label(ax.containers[0])
plt.tight_layout()
plt.savefig("results/type_distribution.png", dpi=300)
plt.show()

plt.figure(figsize=(8,4))
sns.histplot(df['release_year'], bins=30, kde=False)
plt.title("Release year distribution")
plt.xlabel("Release year")
plt.ylabel("Number of titles")
plt.tight_layout()
plt.savefig("results/release_year_hist.png", dpi=300)
plt.show()

import seaborn as sns

res_df = pd.DataFrame([
    ["Logistic Regression", 1.0, 1.0],
    ["KNN", 0.9960272418, 0.9971556278],
    ["Decision Tree", 1.0, 1.0]
], columns=["Model", "Accuracy", "F1"])

plt.figure(figsize=(6,4))
sns.barplot(data=res_df, x="Model", y="F1")
plt.title("Model comparison (F1-score)")
plt.ylim(0.9, 1.01)
for i, v in enumerate(res_df["F1"]):
    plt.text(i, v + 0.001, f"{v:.3f}", ha='center')
plt.tight_layout()
plt.savefig("results/model_comparison.png", dpi=300)
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

y_pred_best = best_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred_best)
disp = ConfusionMatrixDisplay(cm, display_labels=["TV Show", "Movie"])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix – Best Model (Logistic Regression)")
plt.tight_layout()
plt.savefig("results/confusion_matrix_best_logreg.png", dpi=300)
plt.show()

Ks = sorted(sil.keys())
scores = [sil[k] for k in Ks]

plt.figure(figsize=(6,4))
plt.plot(Ks, scores, marker='o')
plt.title("Silhouette score vs K (K-Means)")
plt.xlabel("Number of clusters (K)")
plt.ylabel("Silhouette score")
plt.grid(True)
plt.tight_layout()
plt.savefig("results/silhouette_vs_k.png", dpi=300)
plt.show()

cluster_counts = df_clust['cluster'].value_counts().sort_index()

plt.figure(figsize=(6,4))
sns.barplot(x=cluster_counts.index, y=cluster_counts.values)
plt.title("Number of titles per cluster (K-Means)")
plt.xlabel("Cluster")
plt.ylabel("Count")
for i, v in enumerate(cluster_counts.values):
    plt.text(i, v + 5, str(v), ha='center')
plt.tight_layout()
plt.savefig("results/cluster_sizes.png", dpi=300)
plt.show()